<?php

use Drupal\file\Entity\File;
use Symfony\Component\HttpFoundation\RedirectResponse;

function coronado_recipes_recipe_cancel()
{
  global $base_url;

  $response = new RedirectResponse($base_url . '/admin/content/recipes');
  $response->send();
  return;
}

function coronado_recipes_theme($existing, $type, $theme, $path)
{
  return [
    'coronado_recipess_home_page'       => [
      'template'  => 'home-page',
      'variables' => [
        'filters' => [],
        'bucket_url'=> "https://".\Drupal::config('s3fs.settings')->get('bucket').".s3.amazonaws.com/s3fs-public",
      ],
    ],
    'coronado_recipes_grid'       => [
      'template'  => 'recipes',
      'variables' => [
        'recipes' => [],
        'bucket_url'=> "https://".\Drupal::config('s3fs.settings')->get('bucket').".s3.amazonaws.com/s3fs-public",
      ],
    ],
    'coronado_recipes_detail'   => [
      'template'  => 'detail',
      'variables' => [
        'recipe' => [],
        'bucket_url'=> "https://".\Drupal::config('s3fs.settings')->get('bucket').".s3.amazonaws.com/s3fs-public",
      ],
    ],
  ];
}

function coronado_recipes_preprocess_image_widget(&$variables)
{
  $element = $variables['element'];

  $variables['attributes'] = array('class' => array('image-widget', 'js-form-managed-file', 'form-managed-file', 'clearfix'));

  if (!empty($element['fids']['#value'])) {
    $files = array();
    foreach ($element['fids']['#value'] as $fid) {
      $image = File::load($fid);
      array_push($files, $image);
      $element['file_' . $image->id()]['filename']['#suffix'] = ' <span class="file-size">(' . format_size($image->getSize()) . ')</span> ';
    }

    $file_variables = array();
    foreach ($files as $file) {
      array_push($file_variables, array(
        'style_name' => $element['#preview_image_style'],
        'uri' => $file->getFileUri(),
      ));
    }


    $preview = array();
    foreach ($file_variables as $vfile) {
      array_push($preview, array(
        '#weight' => -10,
        '#theme' => 'image_style',
        '#width' => $vfile['width'],
        '#height' => $vfile['height'],
        '#style_name' => $vfile['style_name'],
        '#uri' => $vfile['uri'],
      ));
    }

    $element['preview'] = $preview;

    // Store the dimensions in the form so the file doesn't have to be
    // accessed again. This is important for remote files.
    $element['width'] = array(
      '#type' => 'hidden',
      '#value' => $file_variables['width'],
    );
    $element['height'] = array(
      '#type' => 'hidden',
      '#value' => $file_variables['height'],
    );
  }

  $variables['data'] = array();
  foreach (\Drupal\Core\Render\Element::children($element) as $child) {
    $variables['data'][$child] = $element[$child];
  }
}
